Part of mandatory tests
secvisogram/secvisogram pull request #186
Opened 2021-08-09 14:18 UTC by domachine

This PR implements some of the mandatory tests mentioned in #36

2021-08-19 17:12 UTC, tschmidtb51 commented on app/lib/shared/Core/entities/DocumentEntity.js
> +          )[0].number !== doc.document.tracking.version
According to [CSAF 6.1.6](https://github.com/oasis-tcs/csaf/blob/master/csaf_2.0/prose/csaf-v2-editor-draft.md#6116-latest-document-version) build metadata is ignored in the comparison.

2021-08-19 21:07 UTC, tschmidtb51 requested changes
@domachine Thanks for implementing the tests.

I have some requests for changes. Please address the comments.

FYI: Also I opened tickets (https://github.com/oasis-tcs/csaf/issues/339, https://github.com/oasis-tcs/csaf/issues/340) for parts of the spec to remove ambiguity.

2021-08-19 21:07 UTC, tschmidtb51 commented on app/tests/shared/coreFixture.js
> +    },
I suggest to add an additional test with semantic versioning here:
```suggestion
    },

    // Fails "6.1.22 Multiple Definition in Revision History"
    {
      valid: false,
      content: {
        ...MINIMAL_DOC,
        document: {
          ...MINIMAL_DOC.document,
          tracking: {
            ...MINIMAL_DOC.document.tracking,
            revision_history: [
              {
                date: '2021-07-20T10:00:00.000Z',
                number: '1.0.0',
                summary: 'Initial version.',
              },
              {
                date: '2021-07-21T10:00:00.000Z',
                number: '1.0.0',
                summary: 'Some other changes.',
              },
            ],
            version: '1.0.0',
          },
        },
      },
    },

2021-08-19 21:09 UTC, tschmidtb51 commented
@domachine I'm sorry about the delayed review.

2021-08-20 11:43 UTC, domachine commented
@tschmidtb51 No problem 🙂 . I addressed the issues. Could you re-check?

2021-08-23 06:45 UTC, tschmidtb51 commented on app/lib/shared/Core/entities/DocumentEntity.js
> +          )[0].number !== doc.document.tracking.version
We will keep track of https://github.com/oasis-tcs/csaf/issues/339 in https://github.com/secvisogram/secvisogram/issues/190.

2021-08-23 06:46 UTC, tschmidtb51 approved these changes
LGTM.

2021-08-23 08:15 UTC, pdamian approved these changes

2021-08-30 13:04 UTC, bentolor approved these changes

2021-08-30 13:06 UTC, merged