Mandatory tests part 5
secvisogram/secvisogram pull request #208
Opened 2021-12-10 10:51 UTC by domachine

This PR includes more mandatory tests:

- 6.1.27.1
- 6.1.27.2
- 6.1.27.3
- 6.1.27.4
- 6.1.27.5
- 6.1.27.6
- 6.1.27.7
- 6.1.27.8
- 6.1.27.10

2021-12-10 12:59 UTC, wrtlbrmpft approved these changes
Looks good to me.

2021-12-20 09:24 UTC, tschmidtb51 requested changes
@domachine: Overall a solid implementation (and shows some room from improvement in the spec...).
Minor comments regarding examples and wording.

As it is the reference implementation, I would like to be strict on the separation of 6.1.27.6 and .7 (even though your idea of checking that in .6 was great => as I said: room for improvement in the spec).

2021-12-20 09:24 UTC, tschmidtb51 commented on app/lib/shared/Core/entities/DocumentEntity/mandatoryTest_6_1_27_6.js
> +  const checkedDocumentCategories = new Set(['security_advisory', 'vex'])
@domachine: This should only test on `security_advisory` as `vex` has a special test for that:
```suggestion
  const checkedDocumentCategories = new Set(['security_advisory'])
```

2021-12-20 09:24 UTC, tschmidtb51 commented on app/lib/shared/Core/entities/DocumentEntity/mandatoryTest_6_1_27_7.js
> +      if (!vulnerability.product_status) return
As 6.1.27.6 (see previous review comment) does not longer covers the part of checking whether the product status is there, it must be implemented here.

2021-12-20 09:24 UTC, tschmidtb51 commented on app/tests/Core/documentTests.js
> +                  text: 'My system test',
Just to make the usage clear => link to example from spec.
```suggestion
                  system_name: 'GitHub Issue',
                  text: 'oasis-tcs/csaf#210',

2021-12-20 09:24 UTC, tschmidtb51 commented on app/tests/Core/documentTests.js
> +            text: 'My system test',
Just to make the usage clear => link to example from spec.
```suggestion
            system_name: 'GitHub Issue',
            text: 'oasis-tcs/csaf#210',

2021-12-20 10:32 UTC, tschmidtb51 commented
@domachine As discussed, please also do 3e0dea6 in a separate PR (new review required as it is just dependency update work as in AP 1).

2021-12-23 09:03 UTC, domachine commented
Alright, I updated the marked parts. Could you recheck my changes @tschmidtb51 ?

2021-12-23 23:47 UTC, tschmidtb51 approved these changes
LGTM. Thank you for the changes.

2021-12-23 23:47 UTC, merged