Correctly check against multiple prefixes
secvisogram/secvisogram pull request #223
Opened 2021-12-23 09:34 UTC by domachine

This addresses the case described here: https://github.com/secvisogram/secvisogram/issues/200#issuecomment-997767861

2021-12-23 10:54 UTC, wrtlbrmpft approved these changes

2021-12-27 12:16 UTC, tschmidtb51 requested changes
I found one minor issue here and suggested a code change. I also added some examples that should pass.

2021-12-27 12:16 UTC, tschmidtb51 commented on app/lib/shared/bcpLanguageTagChecker.js
> +          )
Checking the language is not enough as a prefix might contain other parts. Valid is also:
```
de-CH-1996
pt-BR-abl1943
ja-Latn-hepburn-heploc
sl-rozaj-1994
sl-rozaj-solba-1994
sl-rozaj-bsike-1994
```

Please add them to the tests.

Here is an idea I came up with: Test against the start of the original tag. Feel free to edit that if there is a more elegant way...

```suggestion
          s.prefix.some((p) =>
            tag
              .substring(
                 0,
                 tag.toLowerCase().indexOf(variant.toLowerCase()) - 1
               )
               .toLowerCase()
               .startsWith(p.toLowerCase())
          )
```

2022-01-14 10:07 UTC, domachine commented
Okay, I updated the code. I'm not sure, does that also affect the `extlang` subtag?

2022-01-14 10:37 UTC, tschmidtb51 commented
> Okay, I updated the code. I'm not sure, does that also affect the `extlang` subtag?

@domachine You're right! [BCP 47](https://www.ietf.org/rfc/bcp/bcp47.txt) states in Section 2.2.2. Extended Language Subtags:

> [...]
> 2.  Extended language subtag records MUST include **exactly one
>         'Prefix' field** indicating an appropriate **subtag or sequence of
>          subtags** for that extended language subtag.

2022-01-14 10:55 UTC, domachine commented
Alright, I adapted the code for the extlang check. Could you recheck?

2022-01-14 10:56 UTC, tschmidtb51 commented
> Alright, I adapted the code for the extlang check. Could you recheck?

On my way.

2022-01-14 15:02 UTC, tschmidtb51 approved these changes
LGTM. Happy to get that merged. I discovered a minor bug (#227) in the overall implementation. However, that is not really related to this PR.

2022-01-14 15:06 UTC, merged

2022-01-14 15:11 UTC, tschmidtb51 commented
@domachine Just added the fix for #227 as #228.