Feat/summary modal
secvisogram/secvisogram pull request #305
Opened 2022-08-10 08:10 UTC by valentindey

correction of https://github.com/secvisogram/secvisogram/pull/294 where some git history tangled up

2022-08-10 09:47 UTC, cloeser requested changes
- The modal window always remembers the last input.
  - To replicate open the modal, type something in the summary field and close the modal without saving. Then open it again, the text is still there. (This could be a feature? We remember the input until saving or opening another document etc)
  - But the same happens when saving. When I open the modal again the text is still there. (Document version was < 1.0.0 so it should be empty)
- The modal does not prefill the content of the last revision history item when the version is > 1.0.0

2022-08-11 14:20 UTC, valentindey commented
> * The modal window always remembers the last input.
>       
>       * To replicate open the modal, type something in the summary field and close the modal without saving. Then open it again, the text is still there. (This could be a feature? We remember the input until saving or opening another document etc)
>       * But the same happens when saving. When I open the modal again the text is still there. (Document version was < 1.0.0 so it should be empty)

You're right, I didn't pay enough attention to this. I tried working around this issue in several ways now but wasn't able to _overwrite_ `defaultValue`s of the fields (without introducing other issues).
Truth be told, I don't fully understand what's happening and I could really use some help with that. Maybe @domachine could be the right contact for that :slightly_smiling_face: 

>     * The modal does not prefill the content of the last revision history item when the version is > 1.0.0

I guess you're observing this in case of `advisoryState.type` being `NEW_ADVISORY` which we defined to never pre-fill the fields. When e.g. loading an existing document this should work (with the issue above getting in the way)

2022-08-12 13:27 UTC, valentindey commented
Updated as discussed. Now uses the `onClose` handler of the `dialog` to fully reset the modal window when closing/submitting.

Includes the same for other modals `NewDocumentDialog` and `EditWorkflowStateDialog`.

2022-08-15 14:03 UTC, cloeser approved these changes

2022-08-15 14:03 UTC, merged