Feat/i18n
secvisogram/secvisogram pull request #362
Opened 2022-12-13 14:28 UTC by cloeser

2022-12-14 16:19 UTC, valentindey requested changes

2022-12-14 16:19 UTC, valentindey commented on app/lib/app/SecvisogramPage/View/WizardTab/editors/GenericEditor.js
> +  const description = t(`csaf.${property.metaData?.i18n?.description}`)
The `property.metaData?.i18n?.title` could be `undefined`, same as in `ObjectEditor`

2022-12-15 09:47 UTC, cloeser commented on app/lib/app/SecvisogramPage/View/AboutDialog.js
> +        {t('aboutModal.license')}{' '}
No, same with version. fixed.

2022-12-15 10:31 UTC, valentindey commented on app/lib/app/SecvisogramPage/View.js
> +                              {':'}
Now there's a space but still two colons :sweat_smile: 

![image](https://user-images.githubusercontent.com/8581199/207836522-85865c13-975e-4605-a007-0decb31e9f24.png)

2022-12-15 12:18 UTC, valentindey approved these changes

2022-12-15 13:05 UTC, valentindey approved these changes

2022-12-15 13:06 UTC, merged