Dependency update
secvisogram/secvisogram pull request #444
Opened 2023-04-12 10:36 UTC by reneschultheis

Update react-markdown from 8.0.5 to 8.0.6
Update react-error-boundary from 3.1.4 to 4.0.3
Update i18next from 22.4.13 to 22.4.14
Update @fortawesome/fontawesome-svg-core from 6.3.0 to 6.4.0
Update @fortawesome/fontawesome-common-type from 6.3.0 to 6.4.0
Update @fortawesome/free-regular-svg-icons from 6.3.0 to 6.4.0
Update @fortawesome/free-solid-svg-icons from 6.3.0 to 6.4.0

2023-04-12 11:33 UTC, tschmidtb51 requested changes
Looks like `webpack` wasn't updated (should be >=5.76.0 due to CVE-2023-28154).

The `csaf-validator-lib` did had the `csaf` submodule updated (probably the wrong repo to complain about)....

2023-04-12 13:36 UTC, reneschultheis commented
Webpack was updated to latest Version (5.78.0)
Dependency-Update regarding @reach/combobox currently still pending, due to a webpack compilation error.
Further investigation is planned for the upcoming days.
<img width="889" alt="image" src="https://user-images.githubusercontent.com/48905133/231474843-78375e27-ee85-488f-abe7-953842e382c9.png">

2023-04-13 07:47 UTC, tschmidtb51 commented
> Further investigation is planned for the upcoming days.

Please track that time separately.

2023-04-25 13:32 UTC, StefanNemeth commented
The webpack compilation error occured because one file was not transpiled properly.

Since cypress v10, `app/cypress/plugins/index.cjs` is not used anymore, so we deleted it and moved its webpack options to the proper location.

2023-04-26 05:33 UTC, tschmidtb51 requested changes
One check (Secvisogram CI) is failing. Please see https://github.com/secvisogram/secvisogram/actions/runs/4798282125/jobs/8536363662 and https://github.com/secvisogram/secvisogram/actions/runs/4798282125/jobs/8536363883 and fix this.

BTW: The latest version in the `csaf-validator-lib` announces 1.3.1 while the `csaf-validator-lib/package.json` in here defines it self as 1.3.0. (I'll comment on that also in the organizers' tool...)

2023-04-26 08:52 UTC, StefanNemeth commented
@tschmidtb51 

My bad. Due to caching, the tests ran without any issues.

Seems like `csaf-validator-lib` is using `node-semver` which now uses the node api `util` since we updated to v7.5.0 two weeks ago.

There weren't any issues back then because the tests ran on node, however it now requires a `util`-polyfill to work properly on the browser. We could just make that change here and accept that `csaf-validator-lib` is not a browser-package or fix it within `csaf-validator-lib` by changing the dependency or reverting to the prior version.

2023-05-01 06:20 UTC, tschmidtb51 commented
@StefanNemeth I guess the long term fix would be within `csaf-validator-lib`. I'm okay with fixing it in `secvisogram` or roll back to the prior version as short term (or doing the long term right away...).

2023-05-02 20:41 UTC, tschmidtb51 approved these changes
LGTM

2023-05-03 07:15 UTC, StefanNemeth approved these changes

2023-05-03 07:15 UTC, merged