Invalid regex
secvisogram/secvisogram pull request #49
Opened 2021-05-06 09:33 UTC by tschmidtb51

- resolves #47
- updates patterns to match HTML5 rules

2021-05-06 19:33 UTC, sthagen approved these changes
LGTM

2021-05-07 05:58 UTC, pdamian requested changes
In my opinion the following regex is invalid (it also fails matching CPE examples from Wikipedia):
![image](https://user-images.githubusercontent.com/9308477/117403746-f631f380-af08-11eb-965f-b4ddd7f21cf7.png)

The `/` character (marked red in above screenshot) should be escaped, i.e. `\/`:
![image](https://user-images.githubusercontent.com/9308477/117403798-0cd84a80-af09-11eb-8233-b65dd663f1ab.png)

The same problem is also present in the JSON schema:
https://github.com/oasis-tcs/csaf/blob/master/csaf_2.0/json_schema/csaf_json_schema.json

2021-05-08 05:38 UTC, pdamian commented
> The pictures look like regex101.com with the language `JavaScript`. As they are using `regex` instead of `pattern` it looks like different rules apply. They have to escape `/` since it marks the end of the regex.

Oh, you are absolutely right. I was wrong on that.

2021-05-08 05:38 UTC, pdamian approved these changes

2021-05-10 06:15 UTC, merged