fix: href-clickable
secvisogram/secvisogram pull request #511
Opened 2023-10-24 13:12 UTC by MarcoKorinth

# Changes
HTML rendering was adjusted so that `<a>` tags are only clickable if one of the following conditions apply:
- The url starts with `#`, `mailto`, `tel`, `http` or `ftp`
- The url starts with `data` and has mimetype for `png` or `jpeg`

2023-11-07 23:44 UTC, tschmidtb51 requested changes
Please see my comments.

2023-11-07 23:44 UTC, tschmidtb51 commented on app/cypress/e2e/SecvisogramPage/SecureHref.cy.js
> +      const hasHref = html.match(/<a href=".*test\.org.*">.*<\/a>/)
Please use example.com instead - test.org is IMHO not reserved for test purposes...
```suggestion
      const hasHref = html.match(/<a href=".*example\.com.*">.*<\/a>/)

2023-11-07 23:44 UTC, tschmidtb51 commented on app/cypress/fixtures/secureHrefTests.js
> +        acknowledgments: [{ urls: ['data:image/png;base64,iVBORwtest.org0KGgoAAAANSUhEUgAAA'] }],
Hmm - that doesn't look like a valid base64 to me. But the idea is good  - we should cover both cases (invalid and valid base64).

2023-11-07 23:44 UTC, tschmidtb51 commented on app/cypress/fixtures/secureHrefTests.js
> +    title: 'data href (MIME-type gif) (invalid)',
I like the idea. We should also put that on the "allowed" list. But SVG should be on the block list.

2023-11-07 23:44 UTC, tschmidtb51 commented on app/lib/app/SecvisogramPage/View/shared/HTMLTemplate/Template.html
> +        For the TLP version see: <a {{#secureHref}}{{#url}}{{.}}{{/url}}{{/secureHref}}{{^url}}https://www.first.org/tlp/{{/url}}>{{#url}}{{.}}{{/url}}{{^url}}https://www.first.org/tlp/{{/url}}</a>
Actually, the current implementation breaks the default value (`https://www.first.org/tlp/`) that is inserted if no `url` is given. I guess the following might fix it:
```suggestion
        For the TLP version see: <a {{#secureHref}}{{#url}}{{.}}{{/url}}{{/secureHref}}{{^url}}href=https://www.first.org/tlp/{{/url}}>{{#url}}{{.}}{{/url}}{{^url}}https://www.first.org/tlp/{{/url}}</a>

2023-11-23 11:55 UTC, tschmidtb51 requested changes
Some more comments

2023-11-23 11:55 UTC, tschmidtb51 commented on app/cypress/e2e/SecvisogramPage/SecureHref.cy.js
> +      const hasHref = html.match(new RegExp(`<a href="${url}">.*</a>`))
Please add some comments here.

2023-11-23 11:55 UTC, tschmidtb51 commented on app/cypress/fixtures/secureHrefTests.js
> +    url: 'mailto://user@example.com',
`mailto:` usually does not have the `//`
But happy to test both...

2023-11-23 11:55 UTC, tschmidtb51 commented on app/cypress/fixtures/secureHrefTests.js
> +    url: 'tel://\\+4934587913248',
`tel:` usually does not have the `//`
But happy to test both...

2023-11-23 11:55 UTC, tschmidtb51 commented on app/cypress/fixtures/secureHrefTests.js
> +        acknowledgments: [{ urls: ['tel://+4934587913248'] }],
We can't use a real number here. I checked with the authority, we can use any of those described in https://www.bundesnetzagentur.de/SharedDocs/Downloads/DE/Sachgebiete/Telekommunikation/Unternehmen_Institutionen/Nummerierung/Rufnummern/mittlg148_2021.pdf?__blob=publicationFile&v=1

=> +493023125000

2023-12-04 20:31 UTC, tschmidtb51 approved these changes
LGTM

2023-12-05 10:12 UTC, StefanNemeth approved these changes

2023-12-05 10:35 UTC, merged